services:
  kiro-rs:
    image: ${KIRO_RS_IMAGE:-zyphrzero/kiro-rs:latest}
    container_name: kiro-rs-8088
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "8088:8091"
    volumes:
      - ./data/:/app/config/
    restart: unless-stopped

networks:
  default:
    ipam:
      config:
        - subnet: 172.18.0.0/24
